version: "3.8"

services:
  mysql:    
    image: mysql
    container_name: mysql-test
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: prueba
    volumes:
      - ./data/DB:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  
  db:
        image: mysql:5.7
        container_name: db-mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=admin123
          - MYSQL_DATABASE=my_store
          - MYSQL_USER=nico
          - MYSQL_PASSWORD=admin123
          - MYSQL_PORT=3307
        ports:
            - "3308:3307"

  # workbench:
  #   image: mysql/mysql-workbench
  #   container_name: mysql_workbench
  #   ports:
  #     - 8090:8080
  #   environment:
  #     - MYSQL_SERVER_HOST:mysql,
  #     - MYSQL_SERVER_PORT:3306,
  #     - MYSQL_USER:root,
  #     - MYSQL_PASSWORD:admin123
  #   restart: always
  #   networks:
  #     netplatzi:
  #        aliases:
  #         - workbench    
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - ./workbench:/root/.mysql/workbench
  
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./workbench:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped   
    depends_on:
      - mysql

  phpmyadmin:
      platform: linux/x86_64
      depends_on:
        - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: phpmyadmin
      environment:
        - MYSQL_ROOT_PASSWORD:admin123
        - PMA_HOST:mysql
      ports:
        - 8090:80
      networks:
        netplatzi:
            aliases:
              - phpadmin
networks:
  netplatzi:
    driver: bridge
    ipam:
      driver: default
